# Generated by Django 3.2.4 on 2021-06-26 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='اسم شرکت')),
                ('logo', models.ImageField(upload_to='logo/%Y/%M/%d', verbose_name='لوگو')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن شرکت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
