# Generated by Django 3.2.4 on 2021-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_seller'),
        ('sellers', '0002_seller_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.Product'),
        ),
    ]
