# Generated by Django 3.2.4 on 2021-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('ostan', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('shahr', models.CharField(blank=True, max_length=70, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_shopadmin', models.BooleanField(default=False, verbose_name='مدیر فروشگاه')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
