# Generated by Django 3.2.4 on 2021-06-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shahr',
        ),
    ]
