# Generated by Django 3.2.4 on 2021-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='ادرس محصول')),
                ('photo', models.ImageField(upload_to='product/%Y/%M/%d', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('storage', models.IntegerField(verbose_name='موجودی')),
                ('price', models.PositiveBigIntegerField(default=0.0, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name=' وضعیت انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['status', '-created'],
            },
        ),
    ]
