# Generated by Django 3.2.4 on 2021-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_is_active'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(blank=True, null=True, related_name='seller', to='sellers.Seller'),
        ),
    ]
