# Generated by Django 3.2.4 on 2021-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('phone', models.CharField(max_length=10, verbose_name='ادرس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('website', models.CharField(max_length=100, verbose_name='ادرس سایت')),
                ('instagram', models.URLField(verbose_name='ادرس اینستاگرام')),
                ('twiiter', models.URLField(verbose_name='ادرس توییتر')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
