# Generated by Django 3.2.4 on 2021-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20210610_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
    ]
